@startuml
title Class Diagram for Parser and Input Exceptions
skinparam classAttributeIconSize 0
hide circle
top to bottom direction

class "Exception" as JavaException

class InventoryDockException {
  + InventoryDockException(message: String)
  + InventoryDockException(message: String, cause: Throwable)
}

class InvalidCommandException
class InvalidDateException
class InvalidFilterException
class InvalidIndexException {
  + InvalidIndexException(message: String)
  + InvalidIndexException(message: String, cause: Throwable)
}
class MissingArgumentException {
  + MissingArgumentException(message: String)
  + MissingArgumentException(message: String, cause: Throwable)
}

JavaException <|-- InventoryDockException
InventoryDockException <|-- InvalidCommandException
InventoryDockException <|-- InvalidDateException
InventoryDockException <|-- InvalidFilterException
InventoryDockException <|-- InvalidIndexException
InventoryDockException <|-- MissingArgumentException
@enduml
